# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 845)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(510, 290, 971, 401))
        self.widget_2.setObjectName("widget_2")
        self.QButtonForgotPassword = QtWidgets.QPushButton(self.widget_2)
        self.QButtonForgotPassword.setGeometry(QtCore.QRect(390, 240, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QButtonForgotPassword.setFont(font)
        self.QButtonForgotPassword.setObjectName("QButtonForgotPassword")
        self.login = QtWidgets.QPushButton(self.widget_2)
        self.login.setGeometry(QtCore.QRect(200, 240, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.seePassword = QtWidgets.QCheckBox(self.widget_2)
        self.seePassword.setGeometry(QtCore.QRect(300, 170, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.seePassword.setFont(font)
        self.seePassword.setObjectName("seePassword")
        self.password = QtWidgets.QLineEdit(self.widget_2)
        self.password.setGeometry(QtCore.QRect(260, 110, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.uname = QtWidgets.QLineEdit(self.widget_2)
        self.uname.setGeometry(QtCore.QRect(260, 60, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.uname.setFont(font)
        self.uname.setObjectName("uname")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(60, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.widget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.uname, self.password)
        MainWindow.setTabOrder(self.password, self.seePassword)
        MainWindow.setTabOrder(self.seePassword, self.login)
        MainWindow.setTabOrder(self.login, self.QButtonForgotPassword)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.QButtonForgotPassword.setText(_translate("MainWindow", "ForgotPassword"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.seePassword.setText(_translate("MainWindow", "See Password"))
        self.label.setText(_translate("MainWindow", "User:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
