# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendEmail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1632, 891)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(650, 280, 621, 431))
        self.widget.setObjectName("widget")
        self.QLineEmail = QtWidgets.QLineEdit(self.widget)
        self.QLineEmail.setGeometry(QtCore.QRect(180, 140, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.QLineEmail.setFont(font)
        self.QLineEmail.setObjectName("QLineEmail")
        self.QButtonSend = QtWidgets.QPushButton(self.widget)
        self.QButtonSend.setGeometry(QtCore.QRect(180, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.QButtonSend.setFont(font)
        self.QButtonSend.setObjectName("QButtonSend")
        self.QButtonClear = QtWidgets.QPushButton(self.widget)
        self.QButtonClear.setGeometry(QtCore.QRect(340, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.QButtonClear.setFont(font)
        self.QButtonClear.setObjectName("QButtonClear")
        self.QButtonBack = QtWidgets.QPushButton(self.widget)
        self.QButtonBack.setGeometry(QtCore.QRect(390, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.QButtonBack.setFont(font)
        self.QButtonBack.setObjectName("QButtonBack")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.QButtonSend.setText(_translate("MainWindow", "Send"))
        self.QButtonClear.setText(_translate("MainWindow", "Clear"))
        self.QButtonBack.setText(_translate("MainWindow", "BACK TO LOGIN"))
        self.label.setText(_translate("MainWindow", "Email:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
